### ISSUE TITLE
Spams-python

### ISSUE THREAD

**Issue by krimsonking1999** [ttsuchi/spams-python#1]
Hi,

Sorry to write here because I know this is primarily a mirror, but I can't get spams to install.  

I have tried on both on mac os and a fresh ubuntu 16.04 install and run into gcc errors on both of the os's.  I'll focus on Ubuntu because it is the easiest to re-create.  

I am working in Python2.7 and have installed both using anaconda and python-pip.  I have also installed numpy using pip install for the python-pip.  I have tried to address dependencies by installing build-essential, libatlas-dev, and libatlas3-base. In following your installation instructions I have ensured that I have libblas.so (actually libblas.so and libblas.so.3) and liblapack.so (actually liblapack.so.3 and liblapack_atlas.so.3 [I added 'lapack_atlas' to the libs in setup.py]) are in /usr/lib. In have run apt-get update to ensure I am on a stable build as well. 

For both prefix and build installation I run into some interesting errors.  

Main exit error: 'x86_64-linux-gnu-gcc' failed with exit status 1

Additional warnings and errors thrown:

1. cc1plus: warning command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++

2. spams/linalg/linalg.h:1680:10 error: expected '(' before '__builtin_isnan

3. Warning # warning using deprecated NumPy API

4. warning: comparison between signed and unsigned integer expressions

Do you have any idea what could be going wrong?
